name: suiri

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

env:
  USER_NAME: ${{ secrets.USER_NAME }}
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
